# Change these first
owner: atlas-bi # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: atlas.bi
    url: https://www.atlas.bi
  - name: demo.atlas.bi
    url: https://demo.atlas.bi
  - name: atlas-hub.atlas.bi
    url: https://atlas-hub.atlas.bi
status-website:
  logoUrl: https://atlas.bi/static/img/logo-192x192.png
  name: Atlas Uptime Montitor
  cname: status.atlas.bi
  theme: light
  introTitle: "Atlas Uptime Montitor"
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/atlas-bi/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 6-18 * * *" # ever 5 minutes, from 6 am to 6 pm.
